export const AGENTS_WORKFLOW_YML = [
  'name: Agents Generated PR CI',
  '',
  'on:',
  '  pull_request:',
  '    branches:',
  '      - main',
  '    types: [opened, synchronize, reopened, ready_for_review]',
  '  workflow_dispatch:',
  '    inputs:',
  '      pr:',
  '        description: PR number (optional)',
  '        required: false',
  '        type: string',
  '      sha:',
  '        description: Commit SHA (optional)',
  '        required: false',
  '        type: string',
  '',
  'permissions:',
  '  contents: read',
  '  pull-requests: write',
  '  issues: write',
  '  packages: write',
  '',
  'concurrency:',
  '  group: agents-${{ github.event.pull_request.number || github.run_id }}',
  '  cancel-in-progress: true',
  '',
  'jobs:',
  '  validate:',
  '    name: Validate generated project',
  '    if: |',
  "      (github.event_name == 'pull_request' && startsWith(github.head_ref, 'agents/workflow-')) ||",
  "      (github.event_name == 'workflow_dispatch' && startsWith(github.ref_name, 'agents/workflow-'))",
  '    runs-on: ubuntu-latest',
  '',
  '    steps:',
  '      - name: Checkout',
  '        uses: actions/checkout@v4',
  '',
  '      - name: Setup Node',
  '        uses: actions/setup-node@v4',
  '        with:',
  '          node-version: 20',
  '          cache: npm',
  '',
  '      - name: Install',
  '        run: npm ci',
  '',
  '      - name: Build',
  '        run: npm run build --if-present',
  '',
  '      - name: Test',
  '        run: npm test -- --run',
  '',
  '      - name: Docker metadata',
  '        id: meta',
  '        uses: docker/metadata-action@v5',
  '        with:',
  '          images: |',
  '            ghcr.io/${{ github.repository_owner }}/generated-${{ github.event.repository.name }}',
  '          tags: |',
  '            type=ref,event=pr',
  '            type=sha',
  '',
  '      - name: Set up QEMU',
  '        uses: docker/setup-qemu-action@v3',
  '',
  '      - name: Set up Docker Buildx',
  '        uses: docker/setup-buildx-action@v3',
  '',
  '      - name: Login to GHCR (optional)',
  '        if: ${{ secrets.GITHUB_TOKEN != "" }}',
  '        uses: docker/login-action@v3',
  '        with:',
  '          registry: ghcr.io',
  '          username: ${{ github.actor }}',
  '          password: ${{ secrets.GITHUB_TOKEN }}',
  '',
  '      - name: Build Docker image (best-effort)',
  '        id: docker_build',
  '        continue-on-error: true',
  '        uses: docker/build-push-action@v6',
  '        with:',
  '          context: .',
  '          push: ${{ secrets.GITHUB_TOKEN != "" }}',
  '          tags: ${{ steps.meta.outputs.tags }}',
  '          labels: ${{ steps.meta.outputs.labels }}',
  '',
  '      - name: Deploy to staging (optional)',
  '        id: deploy',
  '        if: ${{ secrets.STAGING_DEPLOY_WEBHOOK != "" }}',
  '        continue-on-error: true',
  '        run: |',
  '          curl -sS -X POST "${{ secrets.STAGING_DEPLOY_WEBHOOK }}" \\',
  '            -H "Content-Type: application/json" \\',
  '            -d "{\\"repo\\":\\"${{ github.repository }}\\",\\"pr\\":\\"${{ github.event.pull_request.number || inputs.pr || \'\' }}\\",\\"sha\\":\\"${{ github.sha }}\\"}"',
  '',
  '      - name: Comment results on PR',
  '        if: ${{ always() && github.event_name == "pull_request" }}',
  '        uses: actions/github-script@v7',
  '        with:',
  '          script: |',
  '            const status = "${{ job.status }}";',
  '            const docker = "${{ steps.docker_build.outcome || \'skipped\' }}";',
  '            const deploy = "${{ steps.deploy.outcome || \'skipped\' }}";',
  '            ',
  '            const lines = [',
  '              "## Agents CI Report",',
  '              "",',
  '              `**Status:** ${status}`,',
  '              `**Docker:** ${docker}`,',
  '              `**Staging Deploy:** ${deploy}`,',
  '              "",',
  '              "- Trigger: PR branch `agents/workflow-*`",',
  '              "- Note: Docker push uses `GITHUB_TOKEN`; staging deploy requires `STAGING_DEPLOY_WEBHOOK` secret.",',
  '            ];',
  '            ',
  '            await github.rest.issues.createComment({',
  '              owner: context.repo.owner,',
  '              repo: context.repo.repo,',
  '              issue_number: context.issue.number,',
  '              body: lines.join("\\n")',
  '            });'
].join('\n');
