import { WorkflowRun } from '../utils/types';
import {
  BranchProtectionSettings,
  GitHubClient,
  PullRequestMergeMethod,
  PullRequestResult
} from '../utils/github';
import { buildArtifactsAndQuality } from './pipeline';

export interface ArtifactManagerConfig {
  githubToken: string;
  githubOwner: string;
  githubRepo: string;
  branchProtection?: ({ enabled: boolean } & BranchProtectionSettings);
  autoMerge?: { enabled: boolean; method?: PullRequestMergeMethod };
}

export class ArtifactManager {
  private github: GitHubClient;
  private branchProtection?: ArtifactManagerConfig['branchProtection'];
  private autoMerge?: ArtifactManagerConfig['autoMerge'];

  constructor(config: ArtifactManagerConfig) {
    this.github = new GitHubClient({
      token: config.githubToken,
      owner: config.githubOwner,
      repo: config.githubRepo
    });

    this.branchProtection = config.branchProtection;
    this.autoMerge = config.autoMerge;
  }

  /**
   * Generate artifacts and create GitHub PR
   */
  async generateAndPublish(
    workflow: WorkflowRun,
    prebuilt?: { files: Record<string, string>; quality: WorkflowRun['quality'] }
  ): Promise<PullRequestResult> {
    // Validate GitHub connection
    await this.github.validateToken();

    // E3-T002: Optionally enforce branch protection on main
    if (this.branchProtection?.enabled) {
      try {
        await this.github.setBranchProtection(this.branchProtection);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.warn('Failed to apply branch protection:', message);
      }
    }

    const built = prebuilt?.files && prebuilt?.quality
      ? { files: prebuilt.files, quality: prebuilt.quality }
      : await buildArtifactsAndQuality(workflow);

    // Attach quality results onto the workflow (returned to client)
    workflow.quality = built.quality ?? undefined;
    workflow.qualityGatePassed = (built.quality?.errors ?? 0) === 0;

    const issuesForLog = built.quality?.issues ?? [];
    if (issuesForLog.some(i => i.tool === 'project' || i.severity === 'error')) {
      console.warn('Generated project has issues:', issuesForLog.slice(0, 10));
    }

    // Create feature branch
    const branchName = await this.github.createBranch(workflow.id);

    // Commit files to branch
    const commitMessage = `AI-Generated: ${workflow.featureRequest}

Workflow ID: ${workflow.id}
Generated by Digital Twin MVP`;

    await this.github.commitFiles(branchName, built.files, commitMessage);

    // Create pull request
    const pr = await this.github.createPullRequest(branchName, workflow);

    // E3-T002: Optionally enable auto-merge on the PR
    if (this.autoMerge?.enabled) {
      try {
        await this.github.enableAutoMerge(pr.number, this.autoMerge.method);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        console.warn('Failed to enable PR auto-merge:', message);
      }
    }

    // Post validation results if there were issues
    const issues = built.quality?.issues ?? [];
    if (issues.length > 0) {
      const top = issues.slice(0, 50).map(i => `- [${i.severity}] ${i.filePath} (${i.tool}): ${i.message}`).join('\n');
      const summary = built.quality
        ? `**Score:** ${built.quality.score}/100\n\n**Errors:** ${built.quality.errors}  |  **Warnings:** ${built.quality.warnings}\n\n**Coverage estimate:** ${built.quality.coverageEstimate}%\n\n**Formatted files:** ${built.quality.formattedFiles}`
        : '';

      const comment = `## Code Quality Report\n\n${summary}\n\n### Findings\n\n${top}\n\n---\n\nIf there are errors, please fix before merging.`;
      await this.github.postPRComment(pr.number, comment);
    }

    return pr;
  }

  /**
   * Check if workflow has artifacts
   */
  hasArtifacts(workflow: WorkflowRun): boolean {
    return workflow.steps.some(s => s.status === 'completed' && s.output);
  }

  /**
   * Get PR status
   */
  async getPRStatus(prNumber: number) {
    return this.github.getPRStatus(prNumber);
  }
}
